Facility CSV Download for Admins
Team-Code-Monkeys/secret-cocktail-web-app pull request #13
Opened 2023-01-19 22:42 UTC by rdeepak2002

- Ability to download facility data as CSV file in admin portal page
- Fix React CSS error with classnames not being camel-case
- Remove TODO where API URL was being printed to console
- Ability to submit login and register page credentials by pressing enter key

2023-01-20 16:25 UTC, Skyline-9 requested changes

2023-01-20 16:25 UTC, Skyline-9 commented on src/adminportal/index.tsx
> +                        facilityDataArr.push(facility[field] ? `${makeStringCSVCompliant(JSON.stringify(facility[field]))}` : "");
refactor `makeStringCSVCompliant to handle` null/empty

2023-01-20 16:25 UTC, Skyline-9 commented on src/adminportal/styles.module.css
> +a,button {
refactor class name

2023-01-20 16:25 UTC, Skyline-9 commented on src/adminportal/index.tsx
> +                    <span>Download Facilities CSV File</span>
Download as CSV File is too verbose for a button, we should shorten this so text doesn't overflow on mobile

2023-01-20 16:27 UTC, rdeepak2002 commented on src/adminportal/index.tsx
> +                    <span>Download Facilities CSV File</span>
Sounds good. Renaming to "Download CSV."

2023-01-21 01:32 UTC, rdeepak2002 commented on src/adminportal/index.tsx
> +                        facilityDataArr.push(facility[field] ? `${makeStringCSVCompliant(JSON.stringify(facility[field]))}` : "");
Done.

2023-01-23 16:27 UTC, Skyline-9 approved these changes
Looks good to me!

2023-01-23 17:42 UTC, merged