Add Airbnb style linting
Team-Code-Monkeys/secret-cocktail-web-app pull request #30
Opened 2023-01-31 02:26 UTC by rdeepak2002

Add Airbnb style linting and GitHub workflow to verify this

2023-01-31 02:39 UTC, Skyline-9 requested changes

2023-01-31 02:39 UTC, Skyline-9 commented on src/authredirect/auth-check.tsx
> +// eslint-disable-next-line @typescript-eslint/naming-convention
Please change this to a file wide disable
`/* eslint-disable @typescript-eslint/naming-convention */`

2023-01-31 02:39 UTC, Skyline-9 commented on src/authredirect/auth-check.tsx
> +// eslint-disable-next-line max-len
Is it really not possible to make this line shorter? We could try to split up like
```
(auth: Auth,
navigate: NavigateFunction,
...
)
```

2023-01-31 02:39 UTC, Skyline-9 commented on src/facility/index.tsx
>                          const isAdmin = idTokenResult?.claims?.admin === true;
Tend to agree with eslint here, maybe we can make this one line without storing the const

2023-01-31 02:39 UTC, Skyline-9 commented on src/facility/index.tsx
> +                        // eslint-disable-next-line @typescript-eslint/no-shadow
Same here, maybe we can make this one line

2023-01-31 02:39 UTC, Skyline-9 commented on src/facility/index.tsx
> +            {/* eslint-disable-next-line @typescript-eslint/no-use-before-define */}
Move `Waves()` and get rid of eslint-disable

2023-01-31 02:39 UTC, Skyline-9 commented on src/login/index.tsx
> +                    // eslint-disable-next-line no-alert
Make this a file-wide disable

2023-01-31 02:39 UTC, Skyline-9 commented on src/navbar/index.tsx
> +                <Logo />
Move `Logo` up and get rid of eslint disable

2023-01-31 02:39 UTC, Skyline-9 commented on src/navbar/index.tsx
> +                <TitleText />
Move `TitleText` up and get rid of the disable

2023-01-31 02:39 UTC, Skyline-9 commented on src/register/index.tsx
> +            // eslint-disable-next-line react/destructuring-assignment
Change to destructuring

2023-01-31 02:39 UTC, Skyline-9 commented on src/register/index.tsx
> +            // eslint-disable-next-line no-alert
Make this file wide disable

2023-02-07 20:45 UTC, rdeepak2002 commented on src/authredirect/auth-check.tsx
> +// eslint-disable-next-line max-len
Done. Updating PR soon.

2023-02-07 20:45 UTC, rdeepak2002 commented on src/authredirect/auth-check.tsx
> +// eslint-disable-next-line @typescript-eslint/naming-convention
Done. Updating PR soon.

2023-02-07 20:47 UTC, rdeepak2002 commented on src/facility/index.tsx
>                          const isAdmin = idTokenResult?.claims?.admin === true;
I'll just merge it into one line:

```setIsAdmin(idTokenResult?.claims?.admin === true);```

2023-02-07 20:48 UTC, rdeepak2002 commented on src/facility/index.tsx
> +                        // eslint-disable-next-line @typescript-eslint/no-shadow
Merged into one line:
```setIsFacility(idTokenResult?.claims?.facility === true);```

2023-02-07 20:49 UTC, rdeepak2002 commented on src/facility/index.tsx
> +            {/* eslint-disable-next-line @typescript-eslint/no-use-before-define */}
Good point. Done.

2023-02-07 20:50 UTC, rdeepak2002 commented on src/login/index.tsx
> +                    // eslint-disable-next-line no-alert
I would like to respectfully disagree with this feedback. We should ultimately replace all alerts with Modals in the long run.

2023-02-07 20:52 UTC, rdeepak2002 commented on src/navbar/index.tsx
> +                <Logo />
Good point. This has now been fixed.

2023-02-07 20:52 UTC, rdeepak2002 commented on src/navbar/index.tsx
> +                <TitleText />
Done ✅

2023-02-07 20:53 UTC, rdeepak2002 commented on src/register/index.tsx
> +            // eslint-disable-next-line no-alert
I would like to disagree. Please refer to my previous comment: https://github.com/Team-Code-Monkeys/secret-cocktail-web-app/pull/30#discussion_r1099217884

2023-02-07 20:58 UTC, rdeepak2002 commented on src/register/index.tsx
> +            // eslint-disable-next-line react/destructuring-assignment
Done ✅

2023-02-07 20:59 UTC, Skyline-9 commented on src/login/index.tsx
> +                    // eslint-disable-next-line no-alert
I would like to respectfully disagree with your disagreement. The convention in focus is not whether alerts are good or bad, but whether eslint ignores should be placed line wide or file wide. Using just one `// eslint-disable` makes the migration to modals much easier. Spamming the disables for every line might create residual comments that we forget to delete

2023-02-07 21:01 UTC, rdeepak2002 commented on src/login/index.tsx
> +                    // eslint-disable-next-line no-alert
I would like to respectfully disagree with your disagreement of my disagreement. If someone adds an alert() in a future commit, the eslint error will not appear for them due to file-wide disabling of this. Thus, we should make this line by line so future commits do not introduce more places where we have to fix this.

2023-02-07 21:02 UTC, Skyline-9 commented on src/login/index.tsx
> +                    // eslint-disable-next-line no-alert
I disrespectfully disagree with your disagreement of my disagreement to your disagreement, when we move to modals we will delete the `//eslint-disable` and ban alerts on entire file

2023-02-07 21:05 UTC, rdeepak2002 commented on src/login/index.tsx
> +                    // eslint-disable-next-line no-alert
I would like to doubly disrespectfully disagree with your disagreement of my disagreement of your disagreement of my disagreement because not doing a file wide disable will make future contributors aware of this issue and encourage them to add a commit where we change from alerts to modals.

2023-02-07 21:07 UTC, Skyline-9 commented on src/login/index.tsx
> +                    // eslint-disable-next-line no-alert
Your opinion is invalid, future contributors will be aware because of this conversation alone

2023-02-07 21:09 UTC, rdeepak2002 commented on src/login/index.tsx
> +                    // eslint-disable-next-line no-alert
I agree. Will use file-wide disabling of this check.

2023-02-07 21:11 UTC, Skyline-9 approved these changes
LGTM, very good work Deeps

2023-02-07 21:11 UTC, merged